### ISSUE TITLE
Sugestão de organização de diretórios do repositório

### ISSUE THREAD

**Issue by mateusqc** [camilacarvalho/PetStore#10]
Sugestão de organização em diretórios, renomeando os diretórios para frontend, backend e um outro para armazenar os arquivos do protótipo inicial do sistema. Com isso ficaria algo assim:

- frontend
- backend
- prototipo

Onde no diretório raiz apenas o README principal do projeto deveria estar.

**Comment by camilacarvalho** [comment]
Muito obrigada pela dica, a alteração já foi feita.
