### ISSUE TITLE
Declaração de listas de objeto

### ISSUE THREAD

**Issue by mateusqc** [camilacarvalho/PetStore#11]
Para as listas utilizadas nos arquivos de rota, recomendo realizar a seguinte mudaça:

Código atual:
```js
favorites = [];
favorites.push(products[1]);
```

Código sugerido:
```js
const favorites = [ products[1] ];
```

Mesmo sendo const, os valores da lista ainda poderão ser acessados e modificados normalmente, entretanto, uma atribuição à variável favorites não será permitida (o que é uma coisa boa, nos garantindo que nenhuma função definida de forma incorreta vai sobrescrever os dados ou causar algum problema).

Esta correção pode se estender para os demais casos encontrados no back-end.

**Comment by camilacarvalho** [comment]
Muito obrigada pela sugestão e explicação. Já fiz a alteração.
