### ISSUE TITLE
Criar cotrollers

### ISSUE THREAD

**Issue by ArthurFerrao** [camilacarvalho/PetStore#12]
Uma sugestão que poderia ser legal é usar controllers para tirar toda aquela lógica dos routes.
[Exemplo usando essa estrutura](https://medium.com/xp-inc/https-medium-com-tiago-jlima-developer-criando-uma-api-restful-com-nodejs-e-express-9cc1a2c9d4d8)

**Comment by camilacarvalho** [comment]
Obrigada pela sugestão. Já criei meus controllers!!
