### ISSUE TITLE
Componente de filtro de categorias de produto não apresenta categorias

### ISSUE THREAD

**Issue by oliveirosnt** [camilacarvalho/PetStore#13]
O componente de filtro de categorias da página inicial não apresenta nenhuma categoria para o usuário escolher, não entendi direito se é pq tu ainda não codou essa parte ou se é um bug mesmo, de toda forma tô cadastrando a issue (pq tem que cadastrar pelo menos uma :P ), no mais tá bem legal o código, parabéns mesmo!

**Comment by camilacarvalho** [comment]
Não faço idéia do que aconteceu quando você executou, mas essa foi uma das primeiras funcionalidades que fiz e nunca deixou de aparecer.
