### ISSUE TITLE
Mostrar em tela a paginação

### ISSUE THREAD

**Issue by LucasCBrasil** [camilacarvalho/PetStore#14]
Vi que já foi implementado componente de paginação, mas não percebi ele sendo usada ao executar o projeto(posso estar enganado), já que ao rodar localmente são exibidos os itens em uma única página, não indicando se há mais páginas ou só aquela. Acredito que seria interessante exibir ao final da listagem, mesmo que os itens exibidos caibam em uma só página, pra deixar claro ao usuário que ali a listagem chegou ao fim.

**Comment by camilacarvalho** [comment]
Tinha pensado em fazera paginação, mas falando com o professor ele disse que não havia necessidade, o que eu já tenho já atende ao que a diciplina pede. Então, não é algo que eu pretendo fazer, mas obrigada pela sugestão.

**Comment by camilacarvalho** [comment]
Tinha pensado em fazera paginação, mas falando com o professor ele disse que não havia necessidade, o que eu já tenho já atende ao que a diciplina pede. Então, não é algo que eu pretendo fazer, mas obrigada pela sugestão.
