### ISSUE TITLE
Mudar a porta que o backend roda

### ISSUE THREAD

**Issue by JonathanAllisson** [camilacarvalho/PetStore#15]
O projeto tá ficando bem bonito e legal, é apenas uma sugestão mas poderia mudar a porta padrão que o backend roda pra não ser a mesma porta padrão do front, é apenas um detalhe sem muita importância, mas fica a sugestão, o projeto tá show :D

**Comment by camilacarvalho** [comment]
Obrigada, fiz a alteração. Realmente isso me chatiava no momento de rodar, mas sempre deixava para alterar depois e é tão simples, né?

**Comment by camilacarvalho** [comment]
Obrigada, fiz a alteração. Realmente isso me chatiava no momento de rodar, mas sempre deixava para alterar depois e é tão simples, né?
