### ISSUE TITLE
Destructuring para props

### ISSUE THREAD

**Issue by AramisAraujo** [camilacarvalho/PetStore#16]
Oi Camila :D
Vi que você usou props em alguns lugares como no card de itens sem tirar vantagem da desestruturação. Acho que isso pode garantir maior legibilidade e melhorar a manutenção do teu código!

dá uma olhada aqui : [link](https://medium.com/@lcriswell/destructuring-props-in-react-b1c295005ce0)

**Comment by camilacarvalho** [comment]
Obrigada Aramis. Gostei demais da dica. Já estou alterando no meu código.
