### ISSUE TITLE
Remover declarações de variáveis com var

### ISSUE THREAD

**Issue by mateusqc** [camilacarvalho/PetStore#18]
Em javascript, declarações de variáveis com `var` quando estamos tratando com aplicações muito grandes podem vir a nos dar problema, dado que uma variável var possui um escopo global.

Ao invés disso, te sugiro declarar variáveis utilizando `let` e `const`. Deve-se priorizar o `const` sempre que possível (para variáveis que não irão possuir atribuições futuras, como por exemplo: listas que serão manipuladas e imports. Caso haja alguma operação de atribuição, utilizar o `let`, que irá permitir atribuições e limitar o escopo da variável criada.

Para mais detalhes, segue um artigo que explica mais detalhadamente as diferenças: https://www.alura.com.br/artigos/entenda-diferenca-entre-var-let-e-const-no-javascript

**Comment by camilacarvalho** [comment]
Obrigada pela dica, já fiz as alterações.
