### ISSUE TITLE
Aumentar a descrição do README

### ISSUE THREAD

**Issue by LucasCBrasil** [camilacarvalho/PetStore#9]
Achei muito interessante o projeto, a página de index está muito interessante e bem codificada, já com uma estrutura de design boa. Só aconselharia realmente explanar mais no README do que o projeto se trata, de quais funcionalidades são implementadas pelo sistema para o usuário.

**Comment by camilacarvalho** [comment]
Obrigada pela sugestão. Concordo que o README precisa ser melhorado.
